version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-app
hooks:
  AfterInstall:
  - location: scripts/install_dependencies.sh
    timout: 300
    runas: root
  ApplicationStart:
  - location: scripts/start.sh
    timout: 300
    runas: root
  ApplicationStop:
  - location: scripts/stop.sh
    timout: 300
    runas: root